### ISSUE TITLE
Nix issue in fluid attack

### ISSUE THREAD

**Issue by tusharrcrm** [NixOS/nix#10942]
[WARNING] Function lib_sast.root.f017.php_sensitive_http_sent failed analyzing Albatross/app/Services/UserpilotService.php with error None
Traceback (most recent call last):
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/utils/function.py", line 136, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/f017/__init__.py", line 46, in php_sensitive_http_sent
    return _php_sensitive_http_sent(shard, method_supplies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/f017/php.py", line 114, in php_sensitive_http_sent
    return get_vulnerabilities_from_n_ids(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/common.py", line 125, in get_vulnerabilities_from_n_ids
    vulnerabilities=tuple(vulns),
                    ^^^^^^^^^^^^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/common.py", line 106, in <genexpr>
    vulns = (
            ^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/f017/php.py", line 105, in n_ids
    if is_insecure_sanitize(graph, n_id):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/f017/php.py", line 94, in is_insecure_sanitize
    return eval_sanitization(graph, n_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/f017/php.py", line 86, in eval_sanitization
    member = get_member(graph, val_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vx4mnq4vrbf6jz68nrqdnskkkvki1y5a-skims/lib_sast/root/f017/php.py", line 33, in get_member
    exp_id = graph.nodes[n_id].get("expression_id")
             ~~~~~~~~~~~^^^^^^
  File "/nix/store/a9n45n1wxcmd2wh6gvx58akxcs37bvk6-python3-3.11.7-env/lib/python3.11/site-packages/networkx/classes/reportviews.py", line 194, in __getitem__
    return self._nodes[n]
           ~~~~~~~~~~~^^^
KeyError: None

**Comment by danmur97** [comment]
This is a fluid attacks skims issue not a nix one. Please create an issue on [universe](https://gitlab.com/fluidattacks/universe/-/issues) instead

**Comment by alejolagosm** [comment]
Hi @tusharrcrm 
We believe we have fixed this problem (As we commented on the issue ://gitlab.com/fluidattacks/universe/-/issues/12359)
Please, if you see any other errors with the scanner, create issues directly on that repository, so as not to bother nix, makes or any other third party maintainers with unrelated problems.
Thanks!

**Comment by cole-h** [comment]
Closing as this doesn't appear to be an issue with Nix itself. Thanks!
