### ISSUE TITLE
Segfault running nix-shell

### ISSUE THREAD

**Issue by he-la** [NixOS/nix#3331]
`nix-shell` seems to segfault no matter what configuration I am running it with. Here's my rudimentary setup, which I believe is as minimal as possible:

`default.nix`:
```
with import <nixpkgs> {};

stdenv.mkDerivation {
	name = "my-little-dev-env";
	builder = ./builder.sh;
	src = if lib.inNixShell then null else ./.;
}
```

`builder.sh`:
```
echo "hi"
```

Output of `nix-shell -vvv 2>&1 >/dev/null | tail -n 15`:
```
acquiring write lock on '/nix/var/nix/temproots/4886'
downgrading to read lock on '/nix/var/nix/temproots/4886'
building of '/nix/store/1b08nh4jq5ls6dn8snwj6wqz1zlqr9yd-bash-interactive-4.4-p23.drv': done
building of '/nix/store/2wkz34gf57xj35mzixwrqly4pj5x5fhz-stdenv-linux.drv': init
building of '/nix/store/2wkz34gf57xj35mzixwrqly4pj5x5fhz-stdenv-linux.drv': loading derivation
acquiring write lock on '/nix/var/nix/temproots/4886'
downgrading to read lock on '/nix/var/nix/temproots/4886'
building of '/nix/store/2wkz34gf57xj35mzixwrqly4pj5x5fhz-stdenv-linux.drv': have derivation
acquiring write lock on '/nix/var/nix/temproots/4886'
downgrading to read lock on '/nix/var/nix/temproots/4886'
building of '/nix/store/2wkz34gf57xj35mzixwrqly4pj5x5fhz-stdenv-linux.drv': done
building of '/nix/store/2wkz34gf57xj35mzixwrqly4pj5x5fhz-stdenv-linux.drv': goal destroyed
building of '/nix/store/1b08nh4jq5ls6dn8snwj6wqz1zlqr9yd-bash-interactive-4.4-p23.drv': goal destroyed
building of '/nix/store/8kzygjhk49lc6ycknziaqiw9rgvjr3c6-bash-4.4-p23.drv': goal destroyed
substitution of '/nix/store/5yhzxsv9kgmjlpvlwkkkj4xp0aglf5df-builder.sh': goal destroyed
[1]    4871 segmentation fault (core dumped)  nix-shell -vvv 2>&1 > /dev/null |
       4872 done                              tail -n 15
```

I'm running a fresh install of nix on archlinux.

Using `gdb` to inspect the coredump, I get the following "backtrace":
```
Reading symbols from /nix/store/6lds7pywa1mvay194h6har2cdkhqw2ly-bash-interactive-4.4-p23/bin/bash...
(No debugging symbols found in /nix/store/6lds7pywa1mvay194h6har2cdkhqw2ly-bash-interactive-4.4-p23/bin/bash)
[New LWP 4871]
Core was generated by `bash /tmp/nix-shell-4871-0/rc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x00007f1debe81ebc in _dl_vdso_vsym () from /lib/libc.so.6
#2  0x00007f1debe0403f in time_ifunc () from /lib/libc.so.6
#3  0x00007f1debfebd7a in _dl_relocate_object () from /nix/store/aag9d1y4wcddzzrpfmfp9lcmc7skd7jk-glibc-2.27/lib/ld-linux-x86-64.so.2
#4  0x00007f1debfe426a in dl_main () from /nix/store/aag9d1y4wcddzzrpfmfp9lcmc7skd7jk-glibc-2.27/lib/ld-linux-x86-64.so.2
#5  0x00007f1debff8509 in _dl_sysdep_start () from /nix/store/aag9d1y4wcddzzrpfmfp9lcmc7skd7jk-glibc-2.27/lib/ld-linux-x86-64.so.2
#6  0x00007f1debfe20aa in _dl_start () from /nix/store/aag9d1y4wcddzzrpfmfp9lcmc7skd7jk-glibc-2.27/lib/ld-linux-x86-64.so.2
#7  0x00007f1debfe1208 in _start () from /nix/store/aag9d1y4wcddzzrpfmfp9lcmc7skd7jk-glibc-2.27/lib/ld-linux-x86-64.so.2
#8  0x0000000000000002 in ?? ()
#9  0x00007ffc04092453 in ?? ()
#10 0x00007ffc04092458 in ?? ()
#11 0x0000000000000000 in ?? ()
```

Obviously it would be helpful to have debug symbols, but I'm not sure which binary I should be debugging here and how to recompile it with debug symbols.

Since the last line of the `nix-shell` output is about the `builder.sh` and the segfault seems to come from `bash` (?) I suspect that that's where the issue is, but I have no idea how to verify this guess. I'd be happy to debug this further, but would need some pointers as to what to as I'm still trying to wrap my head around the nix-world.

**Comment by he-la** [comment]
Overwriting the bash in nix/store with my system's bash fixes the problem. This is either an issue in the bash from nixpkgs (unlikely) or an issue with my system. In any case, it does not seem to be an issue in nix itself, so I'm closing this.

**Comment by JohnAZoidberg** [comment]
Hm, nix shouldn't segfault, so I'd say it's very much an issue of nix.
