### ISSUE TITLE
nix-shell segfault: in Curl_set_in_callback

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nix#3342]
On our CI builds, we consistently see Segfault happening (in about 1 out of 50 builds). The Docker image we use is based on `nixos/nix:2.3`

```
.ci/runner.sh: line 17:    25 Segmentation fault      (core dumped) nix-shell --no-build-output --quiet --run "${ARG}" 2>&1
        26 Done                    | ts '[%Y-%m-%d %H:%M:%S]'
```

```
(gdb) bt
#0  0x00007f0cc3370d91 in Curl_set_in_callback () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#1  0x00007f0cc3352e02 in Curl_debug () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#2  0x00007f0cc3353000 in Curl_infof () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#3  0x00007f0cc338c654 in http2_conncheck () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#4  0x00007f0cc3359677 in extract_if_dead () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#5  0x00007f0cc335d520 in Curl_connect () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#6  0x00007f0cc336f0c7 in multi_runsingle () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#7  0x00007f0cc33703b3 in curl_multi_perform () from /nix/store/8zlwgnsk2mv256pyvvdxiylbcz4b85qz-curl-7.64.0/lib/libcurl.so.4
#8  0x00007f0cc40358b5 in nix::CurlDownloader::workerThreadMain() () from /nix/store/3ds3cgji9vjxdbgp10av6smyym1126d1-nix-2.3/lib/libnixstore.so
#9  0x00007f0cc403744c in nix::CurlDownloader::workerThreadEntry() () from /nix/store/3ds3cgji9vjxdbgp10av6smyym1126d1-nix-2.3/lib/libnixstore.so
#10 0x00007f0cc3db0d7f in ?? () from /nix/store/hlnxw4k6931bachvg5sv0cyaissimswb-gcc-7.4.0-lib/lib/libstdc++.so.6
#11 0x00007f0cc3926ef7 in start_thread () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libpthread.so.0
#12 0x00007f0cc385c22f in clone () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6
```

I'm not sure if this is related to #2733, but I can replicate #2733 sometimes as well.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.13, Alpine Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixpkgs-20.03pre194957.bef773ed53f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

cc @lzaldivarkt

**Comment by edolstra** [comment]
It appears that this problem is fixed in newer versions of curl (the Nix 2.3.3 release links against curl 1.68.0).
