### ISSUE TITLE
No GC root to EvalState.baseEnv

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nix#3444]
Since 0629601da1d163a059fa19004256961f8ecdeb78, there is no gc root to EvalState anymore. However, EvalState contains the main reference to `baseEnv`, that can now get GC'd at unfortunate times, such as during `createBaseEnv`.

Found by playing around with incremental gc. Reproduce:
`GC_ENABLE_INCREMENTAL=1 nix eval -f'<nixpkgs>' hello.drvPath`

**Comment by andir** [comment]
While debugging another issue I also discovered this. 

To add some more context (and not just a me too / +1) this is what I get from GDB when running nix with `GC_ENABLE_INCREMENTAL`:

```[----------------------------------registers-----------------------------------]
RAX: 0x54 ('T')
RBX: 0x5ab3b0 --> 0x5ae940 --> 0x5adf00 --> 0x5ad2a0 --> 0x5adb20 --> 0x5ad400 (--> ...)
RCX: 0x55 ('U')
RDX: 0x7ffff5c4ca80 --> 0x0 
RSI: 0x5b14c0 --> 0x0 
RDI: 0x5b1220 --> 0x0 
RBP: 0x5ab650 --> 0x0 
RSP: 0x7fffffff9bc0 --> 0x0 
RIP: 0x7ffff7e55e1a (<nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+584>:	mov    QWORD PTR [rdx+rax*8+0x10],r12)
R8 : 0x5ae100 --> 0x1 
R9 : 0x3 
R10: 0x0 
R11: 0x1 
R12: 0x7ffff5c4ffe0 --> 0xe 
R13: 0x5ab648 --> 0xea6000000001 
R14: 0x54 ('T')
R15: 0x5b1428 --> 0x5b1438 --> 0x686374616d ('match')
EFLAGS: 0x10202 (carry parity adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff7e55e0f <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+573>:	lea    ecx,[rax+0x1]
   0x7ffff7e55e12 <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+576>:	mov    DWORD PTR [rbx+0x2c8],ecx
   0x7ffff7e55e18 <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+582>:	mov    eax,eax
=> 0x7ffff7e55e1a <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+584>:	mov    QWORD PTR [rdx+rax*8+0x10],r12
   0x7ffff7e55e1f <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+589>:	mov    rax,QWORD PTR [rbx+0x280]
   0x7ffff7e55e26 <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+596>:	mov    rax,QWORD PTR [rax+0x10]
   0x7ffff7e55e2a <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+600>:	mov    rdx,QWORD PTR [rax+0x8]
   0x7ffff7e55e2e <nix::EvalState::addPrimOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&))+604>:	mov    QWORD PTR [rsp+0x10],r15
[------------------------------------stack-------------------------------------]
0000| 0x7fffffff9bc0 --> 0x0 
0008| 0x7fffffff9bc8 --> 0x5b1488 --> 0x5b1498 --> 0x686374616d5f5f ('__match')
0016| 0x7fffffff9bd0 --> 0x7fffffff9bc8 --> 0x5b1488 --> 0x5b1498 --> 0x686374616d5f5f ('__match')
0024| 0x7fffffff9bd8 --> 0x7ffff5c4f540 --> 0xe 
0032| 0x7fffffff9be0 --> 0x7ffff7f2a900 --> 0x0 
0040| 0x7fffffff9be8 --> 0x11 
0048| 0x7fffffff9bf0 --> 0x7fffffff9c00 --> 0x697200686374616d ('match')
0056| 0x7fffffff9bf8 --> 0x5 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x00007ffff7e55e1a in nix::EvalState::addPrimOp (this=this@entry=0x5ab3b0, name="__match", arity=arity@entry=0x2, primOp=primOp@entry=0x7ffff7eae545 <nix::prim_match(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&)>) at src/libexpr/eval.cc:466
466	src/libexpr/eval.cc: No such file or directory.
$ bt
#0  0x00007ffff7e55e1a in nix::EvalState::addPrimOp (this=this@entry=0x5ab3b0, name="__match", arity=arity@entry=0x2, primOp=primOp@entry=0x7ffff7eae545 <nix::prim_match(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&)>) at src/libexpr/eval.cc:466
#1  0x00007ffff7eaad57 in nix::EvalState::createBaseEnv (this=this@entry=0x5ab3b0) at /nix/store/gh9a48qcwzw588vy4w72w93kad0mhhi8-gcc-9.2.0/include/c++/9.2.0/bits/basic_string.h:263
#2  0x00007ffff7e5728f in nix::EvalState::EvalState (this=0x5ab3b0, _searchPath=..., store=...) at src/libexpr/eval.cc:348
#3  0x00000000004d5386 in nix::SourceExprCommand::getEvalState() ()
#4  0x00000000004da3c0 in nix::InstallableValue::toBuildables() ()
#5  0x00000000004d4671 in nix::build(nix::ref<nix::Store>, nix::RealiseMode, std::vector<std::shared_ptr<nix::Installable>, std::allocator<std::shared_ptr<nix::Installable> > >) ()
#6  0x00000000004c109f in CmdBuild::run(nix::ref<nix::Store>) ()
#7  0x00000000004c4283 in nix::StoreCommand::run() ()
#8  0x00000000004e126c in nix::mainWrapped(int, char**) ()
#9  0x00000000004e14bd in std::_Function_handler<void (), main::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#10 0x000000000047fc3e in std::function<void ()>::operator()() const ()
#11 0x00007ffff7b42fc0 in nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) (programName="/nix/store/s1f173m0ayhp4k6iqj83cbly0wq483jb-nix-2.3.3/bin/nix", fun=...) at src/libmain/shared.cc:287
#12 0x00000000004e0bd0 in main ()
#13 0x00007ffff7303d8b in __libc_start_main () from /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6
#14 0x0000000000437e4a in _start ()
```
