### ISSUE TITLE
Assertions aren't well handled with the new error formatting changes

### ISSUE THREAD

**Issue by AmineChikhaoui** [NixOS/nix#3817]
Using nixpkgs 20.03, this should reproduce the issue but probably it's very easy to reproduce with another expression that has an assert:
```
$ gdb --args nix-shell -p python3Packages.gurobipy
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nix-shell...
Reading symbols from /nix/store/268r1ly412r1lcz696z0lmdb851mhy8d-nix-2.4pre20200622_334e26b-debug/lib/debug/.build-id/51/5c6b92a86d8148fc0a2958dd8b39dd64a2774f.debug...
(gdb) r
Starting program: /nix/store/2yhpfgvpc1vxg05xbg9m142i7hdnmbms-system-path/bin/nix-shell -p python3Packages.gurobipy
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/xg6ilb9g9zhi2zg1dpi4zcp288rhnvns-glibc-2.30/lib/libthread_db.so.1".
[New Thread 0x7ffff61c3700 (LWP 7971)]
[New Thread 0x7ffff5842700 (LWP 7972)]
[New Thread 0x7ffff5041700 (LWP 7973)]
[New Thread 0x7ffff4840700 (LWP 7974)]
[New Thread 0x7ffff403f700 (LWP 7975)]
[New Thread 0x7ffff383e700 (LWP 7976)]
[New Thread 0x7ffff303d700 (LWP 7977)]
[New Thread 0x7ffff283c700 (LWP 7978)]
[New Thread 0x7fffda02b700 (LWP 7990)]
[New Thread 0x7fffd982a700 (LWP 7991)]
[Thread 0x7fffd982a700 (LWP 7991) exited]
[New Thread 0x7fffd982a700 (LWP 7992)]
[Thread 0x7fffd982a700 (LWP 7992) exited]
[New Thread 0x7fffd982a700 (LWP 7993)]
[Thread 0x7fffd982a700 (LWP 7993) exited]
terminate called after throwing an instance of 'boost::wrapexcept<boost::io::too_few_args>'
  what():  boost::too_few_args: format-string referred to more arguments than were passed

Thread 1 "nix-shell" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff712b548 in __GI_abort () at abort.c:79
#2  0x00007ffff74e6643 in ?? () from /nix/store/danv012gh0aakh8xnk2b35vahklz72mk-gcc-9.2.0-lib/lib/libstdc++.so.6
#3  0x00007ffff74f2066 in ?? () from /nix/store/danv012gh0aakh8xnk2b35vahklz72mk-gcc-9.2.0-lib/lib/libstdc++.so.6
#4  0x00007ffff74f20b1 in std::terminate() () from /nix/store/danv012gh0aakh8xnk2b35vahklz72mk-gcc-9.2.0-lib/lib/libstdc++.so.6
#5  0x00007ffff74f22e4 in __cxa_throw () from /nix/store/danv012gh0aakh8xnk2b35vahklz72mk-gcc-9.2.0-lib/lib/libstdc++.so.6
#6  0x000000000048a118 in boost::throw_exception<boost::io::too_few_args> (e=...) at include/boost/throw_exception.hpp:63
#7  boost::basic_format<char, std::char_traits<char>, std::allocator<char> >::str[abi:cxx11]() const (this=0x710710) at include/boost/format/format_implementation.hpp:224
#8  0x00007ffff76abdb2 in nix::hintformat::str[abi:cxx11]() const (this=<optimized out>) at src/libutil/fmt.hh:122
#9  nix::operator<< (os=..., hf=...) at src/libutil/error.cc:42
#10 0x00007ffff76af058 in nix::operator<< (out=..., einfo=...) at /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/optional:897
#11 0x00007ffff76b0627 in nix::BaseError::calcWhat[abi:cxx11]() const (this=this@entry=0x7106a0) at src/libutil/error.cc:31
#12 0x00007ffff7aac4fa in nix::BaseError::info (this=0x7106a0) at src/libutil/error.hh:156
#13 nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) (
    programName="/nix/store/2yhpfgvpc1vxg05xbg9m142i7hdnmbms-system-path/bin/nix-shell", fun=...) at src/libmain/shared.cc:316
#14 0x00000000004748fb in main (argc=<optimized out>, argv=<optimized out>) at /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/include/c++/9.2.0/ext/new_allocator.h:80
```

**Comment by AmineChikhaoui** [comment]
@bburdette  I don't know if this was fixed already but FYI.

**Comment by grahamc** [comment]
This is fixed in a later revision. I think the pinned version in Nixpkgs might need to be updated?

**Comment by AmineChikhaoui** [comment]
@grahamc oh great, I'll close then. Sorry I didn't check :-)
