### ISSUE TITLE
nix{,-daemon} segfaults when building a nixosConfig

### ISSUE THREAD

**Issue by Kloenk** [NixOS/nix#4130]
**Describe the bug**

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**
1. use: `github:nixos/nix/58dadf295499588e492dab6bdc5934dc27ad3e64` and `github:nixos/nixpkgs/c9eaddb48b169939f4cee30a796cf55fd9e10a06`
2. build `github:kloenk/nix/beb7c9abd050d62babb02cce5eeac53b8cf249ec#nixosConfigurations.barahir.config.system.build.toplevel`
3. nix-daemon or nix segfaults

**Expected behavior**
A system derivation being build

**`nix-env --version` output**
nix-env (Nix) 3.0pre20201008_58dadf2

**Additional context**
gdb bt:
~~~
#0  0x00007f4a3629e08a in raise () from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6
#1  0x00007f4a36288528 in abort () from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6
#2  0x00007f4a36645693 in ?? () from /nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib/libstdc++.so.6
#3  0x00007f4a36650f06 in ?? () from /nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib/libstdc++.so.6
#4  0x00007f4a36650009 in ?? () from /nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib/libstdc++.so.6
#5  0x00007f4a36650934 in __gxx_personality_v0 () from /nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib/libstdc++.so.6
#6  0x00007f4a36456da3 in _Unwind_RaiseException_Phase2 () from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libgcc_s.so.1
#7  0x00007f4a36457301 in _Unwind_RaiseException () from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libgcc_s.so.1
#8  0x00007f4a366511b7 in __cxa_throw () from /nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib/libstdc++.so.6
#9  0x00007f4a367e3d84 in nix::FdSource::readUnbuffered(unsigned char*, unsigned long) [clone .cold] () from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixutil.so
#10 0x00007f4a3683b2e2 in nix::BufferedSource::read(unsigned char*, unsigned long) () from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixutil.so
#11 0x00007f4a3683bd28 in nix::Source::operator()(unsigned char*, unsigned long) () from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixutil.so
#12 0x000000000046ed14 in unsigned int nix::readNum<unsigned int>(nix::Source&) ()
#13 0x00007f4a36a3c19b in nix::FramedSource::~FramedSource() () from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixstore.so
#14 0x00007f4a36977547 in nix::daemon::processConnection(nix::ref<nix::Store>, nix::FdSource&, nix::FdSink&, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, std::function<void (nix::Store&)>) [clone .cold]
    () from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixstore.so
#15 0x00000000004a0f75 in std::_Function_handler<void (), daemonLoop(char**)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#16 0x00007f4a3685c6ec in std::_Function_handler<void (), nix::startProcess(std::function<void ()>, nix::ProcessOptions const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixutil.so
#17 0x00007f4a36858fc9 in nix::doFork(bool, std::function<void ()>) () from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixutil.so
#18 0x00007f4a3685c609 in nix::startProcess(std::function<void ()>, nix::ProcessOptions const&) () from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixutil.so
#19 0x00000000004a2133 in main_nix_daemon(int, char**) ()
#20 0x0000000000557dcb in nix::mainWrapped(int, char**) ()
#21 0x00007f4a36cc0f6d in nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) ()
   from /nix/store/2qnz1byj61238i9kxk5iq5akfxnam3y7-nix-3.0pre20201008_58dadf2/lib/libnixmain.so
#22 0x000000000045d10b in main ()
~~~

**Comment by Kloenk** [comment]
Seems like that was a SIGABRT. But my client told me something about SIGSEGV, IIRC.

**Comment by aaronjanse** [comment]
I can reproduce this issue. Ignore the issue referenced above; I severely misread it

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
