### ISSUE TITLE
Nix deadlocks on any IFD

### ISSUE THREAD

**Issue by Kha** [NixOS/nix#4235]
**Describe the bug**

Any use of IFD deadlocks on current master.

**Steps To Reproduce**

```
$ nix eval --expr 'import ((import <nixos> {}).writeText "hi" "\"hi\"")' --impure
```

I traced the regression back to e8c379555fa0441c5ab83b8e5a3a106d69fe2507, which certainly sounds right. The reentrant lock is presumably from `LocalStore::isValidPathUncached` inside `LocalStore::registerValidPaths`.

Full stacktrace with `-g3`:
```
#0  0x00007f13abc74d62 in __lll_lock_wait ()
   from target:/nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libpthread.so.0
#1  0x00007f13abc6d721 in pthread_mutex_lock ()
   from target:/nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libpthread.so.0
#2  0x00007f13ac2e9281 in virtual thunk to nix::LocalStore::isValidPathUncached(nix::StorePath const&) ()
   from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#3  0x00007f13ac3618c7 in nix::Store::isValidPath(nix::StorePath const&) ()
   from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#4  0x00007f13ac296526 in nix::hashDerivationModulo[abi:cxx11](nix::Store&, nix::Derivation const&, bool) ()
   from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#5  0x00007f13ac2ee6cf in std::__detail::__variant::__gen_vtable_impl<true, std::__detail::__variant::_Multi_array<void (*)(nix::overloaded<nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputInputAddressed)#2}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputCAFixed)#3}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputCAFloating)#4}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputDeferred)#5}>&&, std::variant<nix::DerivationOutputInputAddressed, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputInputAddressed)#2}, {lambda(nix::DerivationOutputCAFixed)#3}, nix::DerivationOutputCAFloating> const&)>, std::tuple<nix::overloaded<nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputInputAddressed)#2}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputCAFixed)#3}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputCAFloating)#4}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputDeferred)#5}>&&>, std::integer_sequence<unsigned long, 0ul> >::__visit_invoke(nix::DerivationOutputDeferred, nix::overloaded<nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputInputAddressed)#2}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputCAFixed)#3}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputCAFloating)#4}, nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&)::{lambda(nix::DerivationOutputDeferred)#5}>&&) ()
   from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#6  0x00007f13ac2ead23 in nix::LocalStore::checkDerivationOutputs(nix::StorePath const&, nix::Derivation const&) ()
   from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#7  0x00007f13ac2f14ec in nix::LocalStore::registerValidPaths(std::map<nix::StorePath, nix::ValidPathInfo, std::less<nix::StorePath>, std::allocator<std::pair<nix::StorePath const, nix::ValidPathInfo> > > const&)::{lambda()#1}::operator()() const [clone .isra.0] ()
   from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#8  0x00007f13ac2f1963 in nix::LocalStore::registerValidPaths(std::map<nix::StorePath, nix::ValidPathInfo, std::less<nix::StorePath>, std::allocator<std::pair<nix::StorePath const, nix::ValidPathInfo> > > const&) ()
   from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#9  0x00007f13ac2f204e in nix::LocalStore::registerValidPath(nix::ValidPathInfo const&) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#10 0x00007f13ac2f3fce in nix::LocalStore::addTextToStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> > const&, nix::RepairFlag) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#11 0x00007f13ac2829aa in std::__detail::__variant::__gen_vtable_impl<true, std::__detail::__variant::_Multi_array<nix::ref<nix::ValidPathInfo const> (*)(nix::overloaded<nix::daemon::performOp(nix::daemon::TunnelLogger*, nix::ref<nix::Store>, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, unsigned int, nix::Source&, nix::BufferedSink&, unsigned int)::{lambda()#1}::operator()() const::{lambda(nix::TextHashMethod&)#1}, nix::daemon::performOp(nix::daemon::TunnelLogger*, nix::ref<nix::Store>, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, unsigned int, nix::Source&, nix::BufferedSink&, unsigned int)::{lambda()#1}::operator()() const::{lambda(nix::FixedOutputHashMethod&)#2}>&&, std::variant<{lambda()#1}, {lambda(nix::TextHashMethod&)#1}>&)>, std::tuple<nix::overloaded<nix::daemon::performOp(nix::daemon::TunnelLogger*, nix::ref<nix::Store>, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, unsigned int, nix::Source&, nix::BufferedSink&, unsigned int)::{lambda()#1}::operator()() const::{lambda(nix::TextHashMethod&)#1}, nix::daemon::performOp(nix::daemon::TunnelLogger*, nix::ref<nix::Store>, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, unsigned int, nix::Source&, nix::BufferedSink&, unsigned int)::{lambda()#1}::operator()() const::{lambda(nix::FixedOutputHashMethod&)#2}>&&>, std::integer_sequence<unsigned long, 0ul> >::__visit_invoke({lambda(nix::FixedOutputHashMethod&)#2}, nix::overloaded<nix::daemon::performOp(nix::daemon::TunnelLogger*, nix::ref<nix::Store>, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, unsigned int, nix::Source&, nix::BufferedSink&, unsigned int)::{lambda()#1}::operator()() const::{lambda(nix::TextHashMethod&)#1}, nix::daemon::performOp(nix::daemon::TunnelLogger*, nix::ref<nix::Store>, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, unsigned int, nix::Source&, nix::BufferedSink&, unsigned int)::{lambda()#1}::operator()() const::{lambda(nix::FixedOutputHashMethod&)#2}>&&) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#12 0x00007f13ac28798c in nix::daemon::processConnection(nix::ref<nix::Store>, nix::FdSource&, nix::FdSink&, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, std::function<void (nix::Store&)>) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixstore.so
#13 0x00000000004a2f55 in std::_Function_handler<void (), daemonLoop(char**)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#14 0x00007f13ac0a1b0c in std::_Function_handler<void (), nix::startProcess(std::function<void ()>, nix::ProcessOptions const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixutil.so
#15 0x00007f13ac09e4b9 in nix::doFork(bool, std::function<void ()>) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixutil.so
#16 0x00007f13ac0a19f9 in nix::startProcess(std::function<void ()>, nix::ProcessOptions const&) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixutil.so
#17 0x00000000004a4113 in main_nix_daemon(int, char**) ()
#18 0x000000000055cdcb in nix::mainWrapped(int, char**) ()
#19 0x00007f13ac5193ad in nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) () from target:/nix/store/84ypvch47bv3x452nkj3cflwp9b67nrd-nix-2.4pre19700101_0000000000000000000000000000000000000000/lib/libnixmain.so
#20 0x000000000045f05b in main ()
```

**Comment by roberth** [comment]
I was able to reproduce this, but not without Nixpkgs. Ideally we'd find a self-contained example that can be added to the test suite.

<details>

```diff
diff --git a/tests/import-derivation.nix b/tests/import-derivation.nix
index 44fa9a45d..6daa3be96 100644
--- a/tests/import-derivation.nix
+++ b/tests/import-derivation.nix
@@ -15,12 +15,33 @@ let
     assert builtins.pathExists bar;
     import bar;
 
+  writeText = name: text: mkDerivation {
+    inherit name text;
+    passAsFile = [ "text" ];
+    preferLocalBuild = true;
+    allowSubstitutes = false;
+    builder = builtins.toFile "builder.sh" ''
+      mv "$textPath" "$out"
+    '';
+  };
+
+  value2 = import (writeText "hi" "\"hi\"");
+
 in
+{
+  foo = mkDerivation {
+    name = "foo";
+    builder = builtins.toFile "builder.sh"
+      ''
+        echo -n FOO${toString value} > $out
+      '';
+  };
 
-mkDerivation {
-  name = "foo";
-  builder = builtins.toFile "builder.sh"
-    ''
-      echo -n FOO${toString value} > $out
-    '';
-}
+  qux = mkDerivation {
+    name = "qux";
+    builder = builtins.toFile "builder.sh"
+      ''
+        echo -n oh-${toString value2} > $out
+      '';
+  };
+}
\ No newline at end of file
diff --git a/tests/import-derivation.sh b/tests/import-derivation.sh
index 98d61ef49..4e8c3cc34 100644
--- a/tests/import-derivation.sh
+++ b/tests/import-derivation.sh
@@ -2,11 +2,29 @@ source common.sh
 
 clearStore
 
-if nix-instantiate --readonly-mode ./import-derivation.nix; then
+if nix-instantiate --readonly-mode ./import-derivation.nix -A foo; then
     echo "read-only evaluation of an imported derivation unexpectedly failed"
     exit 1
 fi
 
-outPath=$(nix-build ./import-derivation.nix --no-out-link)
+outPath=$(nix-build ./import-derivation.nix --no-out-link -A foo)
 
 [ "$(cat $outPath)" = FOO579 ]
+
+
+if nix-instantiate --readonly-mode ./import-derivation.nix -A qux; then
+    echo "read-only evaluation of an imported derivation unexpectedly failed"
+    exit 1
+fi
+
+outPath=$(nix-build ./import-derivation.nix --no-out-link -A qux)
+
+[ "$(cat $outPath)" = oh-hi ]
+
+# nix eval --expr ./import-derivation.nix  --impure
+
+# Reproduces https://github.com/NixOS/nix/issues/4235 but depends on Nixpkgs
+# timeout 10 nix eval --impure --expr 'import ((import /home/user/system-config/nix/like-nixpkgs {}).writeText "hi" "\"hi\"")'
+
+# Does not reproduce the problem
+timeout 10 nix eval --impure --expr '(import ./import-derivation.nix).qux'
```

</details>

**Comment by Kha** [comment]
Ah, I should have checked for existing tests. So I suppose it's not *any* IFD.
