### ISSUE TITLE
nix::DerivationGoal::registerOutputs(): Assertion `newInfo.ca' failed

### ISSUE THREAD

**Issue by teto** [NixOS/nix#4255]
**Describe the bug**

This is the 2nd time this errors occurs to me:
It happens when I rebuild my flake-based setup:
` src/libstore/build/derivation-goal.cc:3214: void nix::DerivationGoal::registerOutputs(): Assertion `newInfo.ca' failed.`

           PID: 2085 (nix)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Fri 2020-11-13 14:03:08 CET (1min 12s ago)
  Command Line: nix --experimental-features nix-command flakes build git+file:///home/teto/home#nixosConfigurations."jedha".config.system.build.toplevel --impure --no-write-lock-file --override-input nixpkgs-teto /home/teto/nixpkgs --override-input hm /home/teto/hm --override-input nova /home/teto/nova/nova-nix --out-link /tmp/nixos-rebuild.stYtk8/result
    Executable: /nix/store/fb8rfml6sr1d92zyfxzz1ax75a8djjcl-nix-2.4pre20201102_550e11f/bin/nix
 Control Group: /user.slice/user-1000.slice/session-4.scope
          Unit: session-4.scope
         Slice: user-1000.slice
       Session: 4
     Owner UID: 1000 (teto)
       Boot ID: 098bc23ed9fe47e6b5fbcd2e39e68680
    Machine ID: 6ba303eb0232411fbc60369b9affc9e7
      Hostname: jedha
       Storage: /var/lib/systemd/coredump/core.nix.0.098bc23ed9fe47e6b5fbcd2e39e68680.2085.1605272588000000.lz4
       Message: Process 2085 (nix) of user 0 dumped core.
```
with the backtrace
```
#0  0x00007fd6cb5c641a in raise () from /nix/store/kah5n342wz4i0s9lz9ka4bgz91xa2i94-glibc-2.32/lib/libc.so.6
#1  0x00007fd6cb5b0523 in abort () from /nix/store/kah5n342wz4i0s9lz9ka4bgz91xa2i94-glibc-2.32/lib/libc.so.6
#2  0x00007fd6cb5b041f in __assert_fail_base.cold.0 () from /nix/store/kah5n342wz4i0s9lz9ka4bgz91xa2i94-glibc-2.32/lib/libc.so.6
#3  0x00007fd6cb5bed52 in __assert_fail () from /nix/store/kah5n342wz4i0s9lz9ka4bgz91xa2i94-glibc-2.32/lib/libc.so.6
#4  0x00007fd6cbd02579 in nix::DerivationGoal::registerOutputs() () from /nix/store/fb8rfml6sr1d92zyfxzz1ax75a8djjcl-nix-2.4pre20201102_550e11f/lib/libnixstore.so
#5  0x00007fd6cbd03914 in nix::DerivationGoal::buildDone() () from /nix/store/fb8rfml6sr1d92zyfxzz1ax75a8djjcl-nix-2.4pre20201102_550e11f/lib/libnixstore.so
#6  0x00007fd6cbd4f563 in nix::Worker::run(std::set<std::shared_ptr<nix::Goal>, nix::CompareGoalPtrs, std::allocator<std::shared_ptr<nix::Goal> > > const&) ()
   from /nix/store/fb8rfml6sr1d92zyfxzz1ax75a8djjcl-nix-2.4pre20201102_550e11f/lib/libnixstore.so
#7  0x00007fd6cbd42ebb in nix::LocalStore::buildPaths(std::vector<nix::StorePathWithOutputs, std::allocator<nix::StorePathWithOutputs> > const&, nix::BuildMode) ()
   from /nix/store/fb8rfml6sr1d92zyfxzz1ax75a8djjcl-nix-2.4pre20201102_550e11f/lib/libnixstore.so
#8  0x0000000000556c87 in nix::build(nix::ref<nix::Store>, nix::Realise, std::vector<std::shared_ptr<nix::Installable>, std::allocator<std::shared_ptr<nix::Installable> > >, nix::BuildMode)
    ()
#9  0x00000000004f680a in CmdBuild::run(nix::ref<nix::Store>) ()
#10 0x0000000000506638 in nix::StoreCommand::run() ()
#11 0x000000000056e1e8 in nix::mainWrapped(int, char**) ()
#12 0x00007fd6cbfe8edd in nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) ()
   from /nix/store/fb8rfml6sr1d92zyfxzz1ax75a8djjcl-nix-2.4pre20201102_550e11f/lib/libnixmain.so
```

**Steps To Reproduce**
There are too many custom repos involved I hope the backtrace will be enough.

**Comment by teto** [comment]
duplicate of https://github.com/NixOS/nix/issues/4256, github displayed a 404 when submitting this one :/
