### ISSUE TITLE
addPath crashes

### ISSUE THREAD

**Issue by teto** [NixOS/nix#4712]
**Describe the bug**

was upgrading my fork of nixpkgs onto the latest nixos-unstable e019872af81e4013fd518fcacfba74b1de21a50e
but the rebuild crashes with:

**Steps To Reproduce**
```
Core was generated by `nix --experimental-features nix-command flakes build git+file:///home/teto/home'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efec6d632c0 in GC_push_all_eager () from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
[Current thread is 1 (Thread 0x7efec50373c0 (LWP 512160))]
(ins)(gdb) bt
#0  0x00007efec6d632c0 in GC_push_all_eager () from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#1  0x00007efec6d6ff1b in GC_push_all_stacks () from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#2  0x00007efec6d66ae7 in GC_mark_some () from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#3  0x00007efec6d687ed in GC_stopped_mark () from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#4  0x00007efec6d6ce6a in GC_try_to_collect_inner.part.0 ()
   from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#5  0x00007efec6d6d28f in GC_collect_or_expand ()
   from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#6  0x00007efec6d6d518 in GC_allocobj () from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#7  0x00007efec6d6d8af in GC_generic_malloc_inner ()
   from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#8  0x00007efec6d72a24 in GC_generic_malloc_many ()
   from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#9  0x00007efec6d72c92 in GC_malloc_kind () from /nix/store/l6dm2jrz9sz753b31anps4hjjlimp70c-boehm-gc-8.0.4/lib/libgc.so.1
#10 0x00007efec708e2c6 in nix::EvalState::allocValue() ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#11 0x00007efec7092cbc in nix::EvalState::callPrimOp(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#12 0x00007efec70986a3 in nix::EvalState::callFunction(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#13 0x00007efec709884d in nix::ExprApp::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#14 0x00007efec7098828 in nix::ExprApp::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#15 0x00007efec7097d59 in nix::ExprOpNot::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#16 0x00007efec709ba45 in nix::ExprOpAnd::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#17 0x00007efec709843e in nix::EvalState::callFunction(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#18 0x00007efec709884d in nix::ExprApp::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#19 0x00007efec709b648 in nix::ExprOpOr::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#20 0x00007efec709b5d5 in nix::ExprOpOr::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#21 0x00007efec7097d59 in nix::ExprOpNot::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#22 0x00007efec709843e in nix::EvalState::callFunction(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#23 0x00007efec709884d in nix::ExprApp::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#24 0x00007efec709ba45 in nix::ExprOpAnd::eval(nix::EvalState&, nix::Env&, nix::Value&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#25 0x00007efec709843e in nix::EvalState::callFunction(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#26 0x00007efec711b5d0 in nix::addPath(nix::EvalState&, nix::Pos const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nix::Value*, nix::FileIngestionMethod, std::optional<nix::Hash>, nix::Value&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixexpr.so
#27 0x00007efec67dd059 in nix::dump(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nix::Sink&, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixutil.so
#28 0x00007efec67dd242 in nix::dump(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nix::Sink&, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixutil.so
#29 0x00007efec67dd242 in nix::dump(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nix::Sink&, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixutil.so
#30 0x00007efec67dd242 in nix::dump(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nix::Sink&, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>&) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixutil.so
#31 0x00007efec682d9f8 in void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, nix::VirtualStackAllocator, boost::coroutines2::detail::pull_coroutine<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::control_block::control_block<nix::VirtualStackAllocator, nix::sinkToSource(std::function<void (nix::Sink&)>, std::function<void ()>)::SinkToSource::read(char*, unsigned long)::{lambda(boost::coroutines2::detail::push_coroutine<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&)#1}>(boost::context::preallocated, nix::VirtualStackAllocator&&, nix::sinkToSource(std::function<void (nix::Sink&)>, std::function<void ()>)::SinkToSource::read(char*, unsigned long)::{lambda(boost::coroutines2::detail::push_coroutine<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&)#1}&&)::{lambda(boost::context::fiber&&)#1}> >(boost::context::detail::transfer_t) ()
   from /nix/store/52pywkpgzrq8igyz4avlqqs8pgrqxxwa-nix-2.4pre20210326_dd77f71/lib/libnixutil.so

```

**Expected behavior**

**`nix-env --version` output**
nix-env (Nix) 2.4pre20210326_dd77f71

**Additional context**

**Comment by teto** [comment]
It was fully deterministic before I rebased on current unstable. I can now build without issue with the same nix version.

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
