### ISSUE TITLE
macOS installer test failure

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#5381]
**Describe the bug**

I spotted [this installation failure](https://github.com/NixOS/nix/runs/3881024945?check_suite_focus=true) in our `installer_test` on macOS:

```
Alright! We're done!
...

---- Reminders -----------------------------------------------------------------
[ 1 ]
Nix won't work in active shell sessions until you restart them.

/nix:
Error: unable to perform operation.  (-400)
	Error: unknown indexing state.
child_process.js:642
    throw err;
    ^

Error: Command failed: /Users/runner/work/_actions/cachix/install-nix-action/v14/lib/install-nix.sh
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (/Users/runner/work/_actions/cachix/install-nix-action/v14/lib/main.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1071,
  stdout: null,
  stderr: null
}
```

**Expected behavior**

**`nix-env --version` output**

Commit 0fac86fd6feea5f584cb5765b04baeba908bcc03.

**Comment by domenkozar** [comment]
I've released v14.1 that should automatically get picked up by Nix, let's wait until another commit lands and see if it's fixed.
