### ISSUE TITLE
Failures while building derivations on a prefixed nix install

### ISSUE THREAD

**Issue by thecsapprentice** [NixOS/nix#554]
Hey all, 

I'm having some issues with my nix install. Here's the problem: I've installed nix to an alternative prefix, (i.e. not /nix) and I've been trying to install various software packages. This has generally been successful, but I've encountered several packages where I've been hit by an odd error. It's expressed differently each time, but I think the root cause is the same.

Basically, whenever a package tries to access user information (username, home directory, etc..) from the /etc/passwd file, something fails. Now, I'm on a university machine and as such I don't have my user information in the /etc/passwd file, but it is pulled in via a network authentication service ( I suspect Kerberos/AFS involvement, but I honestly don't know enough about their authentication to be sure). 

The following packages (that I've tried thus far) have an issue related to this: coreutils, python 3.4.3, and xdg-utils. Each package exhibits the error in a different fashion. 
- coreutils has problems during validation checks ( which is the problem this guy encountered with coreutils: #512 ) 
- python 3.4.3 fails a check related to pip when it's internal pwd module makes a call to getpwuid (from pwd.h) which returns a NULL value 
- when downloading the source for xdg-utils, git itself fails during checkout with the message 

```
Initialized empty Git repository in      /scratch.1/SOFTWARE/NIX/store/zgnpb41mki1r4f6wrnb8gzmiriyyk94q-xdg-utils-e8ee3b1/.git/
remote: Counting objects: 4533, done.        
remote: Compressing objects: 100% (1424/1424), done.        
remote: Total 4533 (delta 3648), reused 3344 (delta 3084)         
Receiving objects: 100% (4533/4533), 905.44 KiB | 42.00 KiB/s, done. 
Resolving deltas: 100% (3648/3648), done.
fatal: unable to look up current user in the passwd file: no such user
Unable to checkout e8ee3b18d16e41b95148111b920a0c8beed3ac6c from http://anongit.freedesktop.org/git/xdg/xdg-utils.git.
builder for ‘/scratch.1/SOFTWARE/NIX/store/0y275p1gvzjrs07s3qxvdd8z406gq71g-xdg-utils-e8ee3b1.drv’ failed with exit code 1
```

The first two instances I was able to work around by altering the build configuration options for the respective packages, but this last one has me stumped. I could just change where the source is pulled from, but I think after encountering the issue three times, the chances are extremely high that I'll see it again and again. So I think it's time for a more principled solution. Now I don't think this is a nix problem, per se, as it is only occurring from the individual packages, but since it seems to be affecting multiple packages, I'm making the bug report here. 

Does anyone have any incite into what could be the root cause here? And more importantly, what we can do to fix it so prefixed nix installs on network authenticated machines work more reliably?

**Comment by thecsapprentice** [comment]
I've created a test python script that indicates if the problem is occuring:

```python
import os
import pwd

results = pwd.getpwuid( os.getuid() )
print( results )
```

If run from the system installed interpreter, this script delivers the following output:
```
$ python3.4 pwd_test.py 
pwd.struct_passwd(pw_name='nmitchel', pw_passwd='*', pw_uid=4739, pw_gid=4739, pw_gecos='Nathan Mitchell', pw_dir='/u/n/m/nmitchel', pw_shell='/bin/bash')
```

If run from the nix installed version:
```
$ ~/.nix-profile/bin/python3.4 pwd_test.py 
Traceback (most recent call last):
  File "pwd_test.py", line 4, in <module>
    results = pwd.getpwuid( os.getuid() )
KeyError: 'getpwuid(): uid not found: 4739'
```

**Comment by edolstra** [comment]
The problem is not the prefix but the NSS modules configured in `/etc/nsswitch.conf` (e.g. for LDAP). See the recent thread on the mailing list about this: http://comments.gmane.org/gmane.linux.distributions.nixos/17329. Unfortunately there is no simple workaround for this.

**Comment by thecsapprentice** [comment]
Hmmm, interesting. I read through that archive you linked. 

The original poster mentioned something about extending stdenv with libnss_sss. Is this out of the question? If not, how exactly would I go about doing this? Is it as simple as adding another library dependency, or would it involve more in-depth hacking?

**Comment by thecsapprentice** [comment]
Also, for the record, here is my nsswitch.conf:

```
#
# /etc/nsswitch.conf
#
# An example Name Service Switch config file. This file should be
# sorted with the most-used services at the beginning.
#
# The entry '[NOTFOUND=return]' means that the search for an
# entry should stop if the search in the previous entry turned
# up nothing. Note that if the search failed due to some other reason
# (like no NIS server responding) then the search continues with the
# next entry.
#
# Legal entries are:
#
#	nisplus or nis+		Use NIS+ (NIS version 3)
#	nis or yp		Use NIS (NIS version 2), also called YP
#	dns			Use DNS (Domain Name Service)
#	files			Use the local files
#	[NOTFOUND=return]	Stop searching if not found so far
#

passwd:     files sss
shadow:     files sss
group:      files sss

hosts:      dns files

services:   files
networks:   files
protocols:  files
rpc:        files
ethers:     files
netmasks:   files
bootparams: files

netgroup:   nisplus

publickey:  nisplus

automount:  files
aliases:    files
```

**Comment by thecsapprentice** [comment]
For other interested parties, I've compiled a list of other information about this problem:
* http://thread.gmane.org/gmane.linux.distributions.nixos/17329/
* https://github.com/NixOS/nixpkgs/issues/1868
* http://stackoverflow.com/questions/18570177/getpwuid-returns-null-for-ldap-user
* https://fedorahosted.org/sssd/

It looks like the problem is solvable by the addition of the libnss_sss.so.2 library in a place where the dynamic linker can find it. This library is part of the sssd daemon and seems to be currently searched for alongside of glibc.so. Now what I don't know is how the nix installed library would interact with the system installed daemon - there could be some version compatibility issues if one was significantly out of date than the other. But that's the price of running a prefixed nix install, I guess.

**Comment by thecsapprentice** [comment]
Attempting to move forward on this. I've created package descriptions for both sssd and ding-libs (a dependency). However, building sssd fails during the install phase. It appears to be trying to copy a file into another dependency's store location:
```
libtool: install: /scratch.1/SOFTWARE/NIX/store/zms2z2rfrp0ap3b7na08bd515g54iwf8-coreutils-8.23/bin/install -c .libs/memberof.soT /scratch.1/SOFTWARE/NIX/store/xjxish3ss9d50dsz9rjm9h49r0qybqqc-ldb-1.1.20/modules/ldb/memberof.so
/scratch.1/SOFTWARE/NIX/store/zms2z2rfrp0ap3b7na08bd515g54iwf8-coreutils-8.23/bin/install: cannot create regular file '/scratch.1/SOFTWARE/NIX/store/xjxish3ss9d50dsz9rjm9h49r0qybqqc-ldb-1.1.20/modules/ldb/memberof.so': Permission denied
Makefile:6531: recipe for target 'install-ldblibLTLIBRARIES' failed
```

So, not sure what's going on there yet. 

Below are the package descriptions. I want to wait until I've figured out how all this works together before making a official patch. Also, this is my first time making a nix package, so if I've done something wrong, let me know.

```
{ stdenv, fetchurl, pkgconfig}:

stdenv.mkDerivation rec {
                    
   name = "ding-libs-${version}";
   version = "0.4.0";
   src = fetchurl {
       url = "https://fedorahosted.org/released/ding-libs/${name}.tar.gz";
       sha256 = "bdeb90b07ceaa9145e6784ce40a71b69a37fffc7373c51fee258ffffd5390457";
   };
   buildInputs = [ pkgconfig ];
   configureFlags = ''
     
   '';

   meta = {
      description = "DING-LIBS (DING Is Not Glib) are a set of small, useful libraries that SSSD uses and makes available to other projects.";
      homepage = https://fedorahosted.org/sssd;
   };
}
```

```
{ stdenv, fetchurl, pkgconfig, popt, talloc, tdb
, tevent, ldb, ding-libs, pam, openldap, pcre
, krb5, c-ares, bind, cifs_utils, cyrus_sasl
, libnfsidmap, augeas, glib, dbus, libxslt
, docbook5_xsl, docbook_xml_xslt, python3
, libselinux, libsemanage, nss, nspr, libxml2
, ncurses}:

stdenv.mkDerivation rec {
                    
   name = "sssd-${version}";
   version = "1.12.5";
   src = fetchurl {
       url = "https://fedorahosted.org/released/sssd/sssd-1.12.5.tar.gz";
       sha256 = "243d8db7c72ecb21aa9db8a09fe9f9b10049dbdb35a1cc2f55e214f21e3ce256";
   };
   buildInputs = [ pkgconfig  popt talloc tdb tevent ldb 
ding-libs pam openldap pcre krb5 c-ares bind cifs_utils 
cyrus_sasl libnfsidmap augeas glib dbus libxslt docbook5_xsl 
docbook_xml_xslt python3 libselinux libsemanage nss nspr libxml2 
ncurses];
   configureFlags = ''
     --without-samba
   '';
   NIX_CFLAGS_COMPILE="-I${libxml2}/include/libxml2/ -I${ncurses}/include/";
   NIX_LDFLAGS_COMPILE="-L${ncurses}/include/ -lncurses";

   meta = {
      description = "SSSD is a system daemon. Its primary function is to provide access to identity and authentication remote resource through a common framework that can provide caching and offline support to the system.";
      homepage = https://fedorahosted.org/sssd;
   };
}
```

**Comment by thecsapprentice** [comment]
Alright, I think I'm a little stuck. It seems that during installation, sssd tries to install a memberof.so into the ldb modules path. By default (by looking at the configuration script) this path evaluates to a variable set by the ldb entry in pkg-config. Of course, this means that it is referring to a path in the store, which is illegal to write to by another package.

```
configureFlags = ''
     --without-samba --with-ldb-lib-dir=<PATH HERE>
   '';
```

Now, I can specify the directory manually during configure (see above), but I'm a little lost on how to do so. Ideally, I'd like to set this path relative to the store path of sssd, but I can't find a variable that expands to this value. Now the wrinkle is that during the build, this path is used as an rpath argument, so it needs to be an absolute path. I had thought that by specifying `--with-ldb-lib-dir=$out/lib/ldb,` the `$out` would expand to the environment variable `out`, which contains the store path during build. This does not seem to work however. I have also unsuccessfully tried `$$out` and `$prefix` as I noticed that mkDerivation uses a built-in prefix variable during the configure phase. 

Is there a official method of doing this? I assume that this can't be the only package that needs special handling.

**Comment by thecsapprentice** [comment]
Any thoughts on this?

**Comment by adevress** [comment]
Hi,

What you do is really interesting.
Having sssd on nix is a really good thing.

I unfortunatly will not hve time to play with this before this week end, but I would say the good solution is very likely your first idea :

--with-ldb-lib-dir=$out/lib/ldb

Include the module in the sssd derivation itself, it should in this way be included in the correct module directory during installation

**Comment by thecsapprentice** [comment]
Hmm, well, its nice to know I'm on the right track. I suspect my problem is a lack of understanding of the interactions between the expansion rules from the nix packaging language, the bash shell, and the configure script. I too won't have time to look at this until the weekend, but I'm glad someone else has seen it.

**Comment by vrthra** [comment]
@thecsapprentice  @adevress  With a slight change to the `sssd/default.nix`, it will build and install

 ```
{stdenv, fetchurl, pkgconfig, popt, talloc, tdb
, tevent, ldb, dinglibs, pam, openldap, pcre
, libkrb5, c-ares, bind, cifs_utils, cyrus_sasl
, libnfsidmap, augeas, glib, dbus, libxslt
, docbook5_xsl, docbook_xml_xslt, python3
, libselinux, libsemanage, nss, nspr, libxml2
, ncurses}:

stdenv.mkDerivation rec {

   name = "sssd-${version}";
   version = "1.12.5";
   src = fetchurl {
       url = "https://fedorahosted.org/released/sssd/sssd-1.12.5.tar.gz";
       sha256 = "243d8db7c72ecb21aa9db8a09fe9f9b10049dbdb35a1cc2f55e214f21e3ce256";
   };
   buildInputs = [ pkgconfig  popt talloc tdb tevent ldb
dinglibs pam openldap pcre libkrb5 c-ares bind cifs_utils
cyrus_sasl libnfsidmap augeas glib dbus libxslt docbook5_xsl
docbook_xml_xslt python3 libselinux libsemanage nss nspr libxml2
ncurses];
   configurePhase=''
      p=$(cd $out; pwd)
      ./configure --prefix=$prefix --without-samba --with-ldb-lib-dir=$p/lib/ldb
   '';
   NIX_CFLAGS_COMPILE="-I${libxml2}/include/libxml2/ -I${ncurses}/include/";
   NIX_LDFLAGS_COMPILE="-L${ncurses}/include/ -lncurses";

   meta = {
      description = "SSSD is a system daemon. Its primary function is to provide access to identity and authentication remote resource through a common framework that can     provide caching and offline support to the system.";
      homepage = https://fedorahosted.org/sssd;
   };
}

```
Installing,
```
bash-4.2$ nix-env -i sssd -f $NIXPKGS 
replacing old ‘sssd-1.12.5’
installing ‘sssd-1.12.5’
bash-4.2$ find /scratch/gopinatr/nix -name libnss_sss\*
/scratch/gopinatr/nix/store/dmfjgdg2c09r1vgm6kr30wq59f1wvahy-sssd-1.12.5/lib/libnss_sss.la
/scratch/gopinatr/nix/store/dmfjgdg2c09r1vgm6kr30wq59f1wvahy-sssd-1.12.5/lib/libnss_sss.so.2
/scratch/gopinatr/nix/store/rjb7r69cgz030zcdb1f2cjhyhf0czbd5-user-environment/lib/libnss_sss.la
/scratch/gopinatr/nix/store/rjb7r69cgz030zcdb1f2cjhyhf0czbd5-user-environment/lib/libnss_sss.so.2
/scratch/gopinatr/nix/store/fkj4xi5zdn4d3xw8ysjkqxmz2q5hracn-user-environment/lib/libnss_sss.la
/scratch/gopinatr/nix/store/fkj4xi5zdn4d3xw8ysjkqxmz2q5hracn-user-environment/lib/libnss_sss.so.2
bash-4.2$ ls -alt ~/.nix-profile/lib/libnss_sss.*
lrwxrwxrwx. 1 gopinatr upg44172 90 Dec 31  1969 /nfs/stak/students/g/gopinatr/.nix-profile/lib/libnss_sss.la -> /scratch/gopinatr/nix/store/dmfjgdg2c09r1vgm6kr30wq59f1wvahy-sssd-1.12.5/lib/libnss_sss.la
lrwxrwxrwx. 1 gopinatr upg44172 92 Dec 31  1969 /nfs/stak/students/g/gopinatr/.nix-profile/lib/libnss_sss.so.2 -> /scratch/gopinatr/nix/store/dmfjgdg2c09r1vgm6kr30wq59f1wvahy-sssd-1.12.5/lib/libnss_sss.so.2
```
But your python script still fails.
```
bash-4.2$ ~/.nix-profile/bin/python3 x.py
Traceback (most recent call last):
  File "x.py", line 4, in <module>
    results = pwd.getpwuid( os.getuid() )
KeyError: 'getpwuid(): uid not found: 44172'
```
Any idea where to go from here?

**Comment by benwbooth** [comment]
I made a pull request for the sssd package and all its dependencies: NixOS/nixpkgs#14697

Unfortunately, I got stuck trying to figure out how to get libnss_sss.so into the glibc lib folder. On my own NixOS VM, I added a custom initrd script that just copies the file into place on boot. For a prefixed nix install, you could just manually copy the file.

**Comment by vrthra** [comment]
@benwbooth I am checking out your package for nix prefixed install. Could you please share the instructions to update the glibc/lib folder for prefixed install?

**Comment by benwbooth** [comment]
@vrthra Just go into your /nix/store and copy the file from the sssd/lib folder to the glibc/lib folder manually. Of course if glibc is updated you'll have to do it again. The NixOS devs need to come up with a way to get that file into the glibc binary package in order to merge my pull request, but that hasn't happened yet.

**Comment by adevress** [comment]
@vrthra  It will not happen. derivation are immutables, you can not modify a glibc already compiled.

The way this can of thing is usually done is through wrapper. However here it is impossible because the glibc is use by EVERYTHING and create a wrapper for the entire world does not sound reasonnable to me.

I see however few possible workarounds :

1 - recompile the glibc a second time, add to it all nss wrappers and reuse it as default stdenv. However it imply to recompile ALL packages

2- setup LD_LIBRARY_PATH ALL the time to the ssd libnss folder.... This will work but it's particularly dirty because it will make use of LD_LIBRARY_PATH for everything, which  we try to avoid

3- Patch the glibc to make it load the NSS_PLUGINS through a specific environment variable ( something like "GLIBC_NSS_PLUGIN_PATH" and setup this variable as a setup_hook.

**Comment by liori** [comment]
@adevress I'd like to note that (1) doesn't look that bad. The reporter's problem, which happens to be very similar to mine, is with a nix installation with a custom path—thereby requiring recompilation of everything anyway. It would certainly be acceptable to me.

**Comment by vrthra** [comment]
For any one hitting up on this issue, here is a _work around_ that will get you a workable prefixed nix install. Make sure that `glibc-locale` is installable with  [#15910](https://github.com/NixOS/nixpkgs/issues/15910) work around. Then install `sssd` using [#14697](https://github.com/NixOS/nixpkgs/pull/14697). Now, use the _hack_ above, and copy the `libnss_sss.so` to `glibc/lib`

First, make sure this hack is needed : `pwd_test.py` from the bug report.
```
import os
import pwd
print(pwd.getpwuid( os.getuid()))
```
Use a python from nix
```
$ ~/.nix-profile/bin/python3 pwd_test.py
Traceback (most recent call last):
  File "pwd_test.py", line 4, in <module>
    print(pwd.getpwuid( os.getuid() ))
KeyError: 'getpwuid(): uid not found: 44172'
```

First figure out where the libnss libraries are (in glibc).
```
bash-4.2$ find /scratch/gopinatr/nix -name libnss\* | grep glibc 
/scratch/gopinatr/nix/store/0ixz4a4zypi37k19c1gq6jhrw5ziw8yh-glibc-2.23/lib/libnss_nisplus.so.2
/scratch/gopinatr/nix/store/0ixz4a4zypi37k19c1gq6jhrw5ziw8yh-glibc-2.23/lib/libnss_compat.so.2
...
```
Next, make the directory readable.
```
chmod 777 /scratch/gopinatr/nix/store/0ixz4a4zypi37k19c1gq6jhrw5ziw8yh-glibc-2.23/lib/
```
Now find where the libnss_sss.so is
```
bash-4.2$ find /scratch/gopinatr/nix -name libnss_sss\* | grep sssd
/scratch/gopinatr/nix/store/22fa7cq0wkn9l7329q9d550xgp9w6bff-sssd/lib/libnss_sss.la
/scratch/gopinatr/nix/store/22fa7cq0wkn9l7329q9d550xgp9w6bff-sssd/lib/libnss_sss.so.2
```
copy it over
```
cp /scratch/gopinatr/nix/store/22fa7cq0wkn9l7329q9d550xgp9w6bff-sssd/lib/libnss_sss.so.2 /scratch/gopinatr/nix/store/0ixz4a4zypi37k19c1gq6jhrw5ziw8yh-glibc-2.23/lib/
```
And turn the permissions off
```
chmod 555 /scratch/gopinatr/nix/store/0ixz4a4zypi37k19c1gq6jhrw5ziw8yh-glibc-2.23/lib/
```
Now try again
```
$ ~/.nix-profile/bin/python3 pwd_test.py
pwd.struct_passwd(pw_name='gopinatr', pw_passwd='*', pw_uid=44172, pw_gid=16473, pw_gecos='Rahul Gopinath', pw_dir='/nfs/stak/students/g/gopinatr', pw_shell='/bin/zsh')
```

**WARNING**: this is not a solution, but if you are stuck trying to use Nix in a university cluster, with a prefixed nix, this might be of help.

**Comment by adevress** [comment]
@vrthra Yes, but that's a hack unfortunatly

This problem illustrate a more general issue about Nix and plugin management in general.

**Comment by vrthra** [comment]
@adevress I agree, this is just a temporary hack since it was a blocking issue for me, and I suspected for others as well using prefixed install.

I noticed that not all packages require the `libnss_sss` plugin. Only a few packages do (git, redo, python, etc) that uses `getpwuid`. So why not create a second package `glibc-with-plugins`, copy over the current `glibc` installation, and update with `libnss_sss` (and any other plugins)? Then the few packages that require `libnss_sss` plugin can depend on the `glibc-with-plugins` instead of standard glibc, and we wont cause the world to be rebuilt. Would this be acceptable?

**Comment by benwbooth** [comment]
@vrthra Is there some way to get a comprehensive list of packages which need libnss_sss? I know `perl` also needs it.

**Comment by vrthra** [comment]
@benwbooth We might zgrep (or extract the sources and grep) the /nix/store for `getpwuid ` on a full build I think.

**Comment by vrthra** [comment]
@benwbooth There is also the possibility of replacing [runtime dependencies](https://nixos.org/wiki/Security_Updates). It is currently used for security related updates, but I wonder if it can be a more general update mechanism.

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
